### ISSUE TITLE
System freeze upon server join

### ISSUE THREAD

**Issue by Searchndstroy** [Thinkofname/steven#38]
When I join a server, my system freezes.
I have to cut the computer's power to restart it.

The server used is a Vanilla 1.9.2 server which has not been modified. Latest Spigot produces the same result. It is ran with "java -jar minecraft_server.jar"

There are no logs involved in this event, as any process in the background seems to freeze as well. I have tested this by repeatedly writing to a file on disk with the current time, and the last **readable** written time corresponds to the system's time at the time of freezing. After that, an amount of zeroes are written (I do not know what writes them and I cannot predict how many are written).
**This goes for logs within var/log as well, except it may or may not write an unpredictable amount of zeroes.**

When I join the server, my monitor freezes to its current frame and never updates. In this frame, **no entities or chunks** are visibly loaded. I can only see the sun in the sky.

The title screen shows no issues at all.

System Info:
 - OS: Ubuntu 15.10 64bit
 - Processor: AMD A8-3520M APU with Radeon(tm) HD Graphics × 4 
 - Graphics: AMD Radeon HD 6620G
 - Graphics-Driver: flgrx/flgrx-updates (occurs with both)

The issue does **not** occur when I use the xserver-xorg-video-ati driver.

Release and Debug builds produce the same result.

This issue occurs with the latest code here as of time of writing, or all code up to and including commit https://github.com/Thinkofname/steven/commit/2acfa47491caee827d0a49f40461e261e38792d8.

There is no build which has not produced this result.

**Comment by Thinkofname** [comment]
I've had someone else (on windows) with an AMD card saying it causes the driver to crash completely when joining a server. Guessing the linux driver isn't as graceful with that.

I don't have an AMD card available currently to debug with and due to it crashing in the driver its extremely hard to track down. Anyone have any knowledge on how to find/fix this?

**Comment by bjorn3** [comment]
Maybe add a write to a file with the current OpenGL function name to the gl wrapper.

**Comment by Thinkofname** [comment]
There are a few tools around that do that already, if someone feels like hooking one up and testing that would be great.

**Comment by bjorn3** [comment]
Do they flush the os write buffer after write?

**Comment by Thinkofname** [comment]
Found an old AMD card lying around, didn't crash but players/signs (any using the model system) didn't work. No opengl errors reported though.

@Searchndstroy Out of interest is the sun visible on the menu screen?

**Comment by Searchndstroy** [comment]
@Thinkofname Yes.

**Comment by Thinkofname** [comment]
hmm, that uses the same system as the other models (but different shader). Maybe the issue is with that?

**Comment by Thinkofname** [comment]
@Searchndstroy could you try latest? https://ci.appveyor.com/project/thinkofdeath/steven-rust/build/88 (64bit is still building currently)

**Comment by Searchndstroy** [comment]
Latest code from https://github.com/Thinkofname/steven/commit/75fb828a8919c23155327e72f4dd394a87547ea8?

**Comment by Thinkofname** [comment]
yes

**Comment by Searchndstroy** [comment]
Issue appears to have been resolved.

Thanks!

**Comment by Thinkofname** [comment]
\o/ apparently AMD's implementation of glMultiDrawElements is broken
