### ISSUE TITLE
Fix unchecked (un)safe gl functions

### ISSUE THREAD

**Issue by bjorn3** [Thinkofname/steven#39]
Its for example possible to create a undefined drawtype on which calling draw functions is unsafe.

Maybe use enums.

**Comment by Thinkofname** [comment]
Its meant to be pretty raw gl bindings with minimum checks. In the future switching to gluim would be a good option but for now these bindings are fine (I actually like working with raw opengl)

**Comment by bjorn3** [comment]
I mean they are marked as safe but aren't.

**Comment by Thinkofname** [comment]
Mainly for convenience. The ecs system has methods like that too.
