### ISSUE TITLE
Use glium?

### ISSUE THREAD

**Issue by Thinkofname** [Thinkofname/steven#40]
Couple of points:

* Is everything we do possible with glium?
* Do we switch back to glutin for this or stick with sdl2? (i'd prefer sdl2 as its more complete)
* Do we gain much from doing this?
* Performance cost/benefit from doing this?
* Anyone insane enough to do this?

cc @Scetch @TheUnnamedDude

**Comment by bjorn3** [comment]
I think we should have two renderers in the code and when the glium renderer is finished we should benchmark them.

When you want a plugin interface there isn't anybody who wants a crashing program due to unsafe interfaces.

**Comment by Thinkofname** [comment]
Rendering wouldn't be exposed to an plugin interface (if we even have one). This is purely internal

**Comment by Thinkofname** [comment]
Not going to happen any time soon. Not worth the work
