### ISSUE TITLE
(minor) Skin rendering wrong

### ISSUE THREAD

**Issue by XDjackieXD** [Thinkofname/steven#43]
It seems like the UV mapping for the skin is somehow wrong.
Nothing with high priority (literally the last issue in the current list that should be fixed ^^).

![auswahl_691](https://cloud.githubusercontent.com/assets/4963868/14465981/4b9d906e-00d5-11e6-9b3f-d10fd197f45e.png)
(sry for the tearing. it sometimes happens with screenshots made using shutter...)

**Comment by Thinkofname** [comment]
Not sure I see the issue?

**Comment by XDjackieXD** [comment]
the left side of the leg is mapped wrong (http://www.minecraft-skin-viewer.net/?username=XDjackieXD)

**Comment by Thinkofname** [comment]
Ah its an old style skin (not using the 64x64 texture but the old 64x32 texture)

**Comment by XDjackieXD** [comment]
Yes I have a new one already but I still play 1.7.10 modded sometimes and the new one looks silly in 1.7.10 so I left the old one
