### ISSUE TITLE
Cannot build steven_resources crate from clean build

### ISSUE THREAD

**Issue by evotopid** [Thinkofname/steven#53]
I tried building steven with the current Rust nightly toolchain (2016-06-23) but it keeps failing because the assets aren't copied to the out directory of the crate.

I tried inspecting resources/build.rs and so far I know build_map creates the out array correctly, ie. this resource.rs file is generated as intended:

    pub fn get_file(name: &str) -> Option<&'static [u8]> {
        match name {
            "assets/steven/logo/textures.txt" => Some(include_bytes!("../assets/steven/logo/textures.txt")),
            "assets/steven/logo/logo.txt" => Some(include_bytes!("../assets/steven/logo/logo.txt")),
            "assets/steven/textures/environment/clouds.png" => Some(include_bytes!("../assets/steven/textures/environment/clouds.png")),
            "assets/steven/textures/gui/cog.png" => Some(include_bytes!("../assets/steven/textures/gui/cog.png")),
            "assets/steven/models/block/missing_block.json" => Some(include_bytes!("../assets/steven/models/block/missing_block.json")),
            "assets/steven/blockstates/missing_block.json" => Some(include_bytes!("../assets/steven/blockstates/missing_block.json")),
            "assets/minecraft/textures/font/ascii.png" => Some(include_bytes!("../assets/minecraft/textures/font/ascii.png")),
            "assets/minecraft/texts/splashes.txt" => Some(include_bytes!("../assets/minecraft/texts/splashes.txt")),
            _ => None
        }
    }

But the files aren't being copied to the build directory in my case. I'm not sure if the `resources/build.rs` script should be modified to copy the files to the appropriate location, use the correct path (maybe building with absolute paths is an option?) or if something in my environment is not correct.

**Comment by Thinkofname** [comment]
Apparently a change in rust/cargo broke this, shame. Haven't had the time to work on steven for a while and i'm not sure when I will so this might not get fixed.

**Comment by ZombiePork** [comment]
It would be so much to me if you could fix it. Whenever you have the time,
I need to get it working as soon as possible. I've kinda promised a friend.
Thanks for replying!
