### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by ZombiePork** [Thinkofname/steven#55]
I've been trying different versions of rust. Uninstalling, and alot more but I've been getting the same errors. I did a post on reddit and I would really love some help. I've been wanting to add my own features to Steven for a long time. 

Here's the post with a picture of the main error
reddit.com/r/rust/comments/4qe4py/rust_compiling_bug/

I know you stopped working on this project but I would like to be able to compile to start my own. Thanks :)

**Comment by Thinkofname** [comment]
That reddit thread suggests that doing `cargo clean` would allow the project to compile, have you tried that?

**Comment by ZombiePork** [comment]
Yes I have done that. In many versions of rust too.

**Comment by ZombiePork** [comment]
@Thinkofname It's so annoying. It looks like it's about to work and boom, errors.

**Comment by Thinkofname** [comment]
Given its an error in the compiler I suggest you ask the rust devs. Nothing I can do
