### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329

### ISSUE THREAD

**Issue by satoshinm** [Thinkofname/steven#69]
After applying the workaround in https://github.com/Thinkofname/steven/issues/67 and fix in https://github.com/Thinkofname/steven/pull/68 I was able to get steven to build and run (rustc 1.19.0-nightly (e17a1227a 2017-05-12) on macOS Sierra), however after a few seconds on the launch screen it invariably crashes before I can login, here is the log with RUST_BACKTRACE=1:

```
[main.rs:184][INFO] Starting steven
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::option::Option<T>>::unwrap
  10: sdl2::event::Event::from_ll
  11: sdl2::event::poll_event
  12: <sdl2::event::EventPollIterator<'a> as core::iter::iterator::Iterator>::next
  13: steven::main
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start
```

<img width="938" alt="screen shot 2017-05-13 at 11 23 25 pm" src="https://cloud.githubusercontent.com/assets/26856618/26031742/4010a6c8-3833-11e7-8d80-2b47f9f1723f.png">

**Comment by Thinkofname** [comment]
The crash should be fixed, no idea about the rendering issue you have though
